### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by olyop** [summernote/skunkworks#4]
Keyboard shortcuts not working anymore. When I implemented this into our application, all keyboard shortcuts were working. However, recently (not sure when) all have stopped working. Since we have not updated any of our dependencies since then my best guess is that a new version of the browser has broken this. 

I thought I would open this issue so we can both figure out the problem.

Codepen: [https://codepen.io/olyop/pen/KKBewvG](https://codepen.io/olyop/pen/KKBewvG). I have just pasted the current summernote build javascript and css into the codepen just like in our environment. The fonts aren't working but shouldn't cause a problem.

Summernote Skunkworks version: Compiled Date: 2023-01-27T00:53Z
jQuery version: v3.6.3
Bootstrap Version: v4.4.1
Chrome: 109.0.5414.120
Edge: 109.0.1518.70
OS: Windows 11 & Fedora Linux 37

**Comment by DennisSuitters** [comment]
![image](https://user-images.githubusercontent.com/32765473/215002024-b8efc1bb-1c4a-420a-b06b-dbcfbef435fa.png)

As you can see, I inserted a horizontal rule ctrl+enter and opened the picture dialog ctrl+k.

I'm using Chrome Version 109.0.5414.119 (Official Build) (64-bit) which was updated 2 days ago via updates, so could be the .120 version. I'm also using Linux Mint (Debian).

I couldn't see anything else interfering with things. Have you tried it without Bootstrap?

**Comment by olyop** [comment]
@DiemenDesign Thanks for getting back to me, appreicate your quick response. Your right that one works as well as the Ctrl+\ which is good. But still others don't work. Including bold, underline, strikethrough and italic which can be seen in the codepen. Yes we use bootstrap in our app which is why I choose this version of summernote, but in the codepen it's replicable without it.

**Comment by DennisSuitters** [comment]
hm, I wonder what's going on then, and yes the other shortcuts are not working. I'm in the middle of updating the ordering system in AuroraCMS atm, once that's done and pushed to the project as a new release, I'm planning on spending time on more improvements of Skunkworks version of Summernote. Hopefully, in the next couple of days, as I'm also busy doing farm stuff, if it rains like it's looks it's going to, I'll be working on code.

**Comment by olyop** [comment]
No worries @DiemenDesign thanks for looking into it. I tried to debug this myself but couldn't get anywhere. Let me know if there's anything I can help with.

**Comment by olyop** [comment]
Any updates on this @DiemenDesign ?

**Comment by olyop** [comment]
@DiemenDesign I have tried to debug this myself and noticed that the shortcuts are working it's just for some reason they are firing twice.

If I comment out this [line](https://github.com/summernote/skunkworks/blob/develop/src/js/module/Editor.js#L376) then everything seems to work but obviously I don't have a full understanding.

**Comment by DennisSuitters** [comment]
Just getting a chance to look at this a bit more. It's weird without your modification, some shortcuts work, such as CTRL_K to open the image dialog, but CTRL+B to bold selected text doesn't. Commenting out the line you suggested, has the opposite effect.
So far, I haven't been able to track down why.

**Comment by DennisSuitters** [comment]
I've pushed changes, commenting out what you found, and as you discovered, the shortcuts work again, I've gone through several of the source files related to how shortcuts work, and there's no reason why those lines of code were disabling some of the shortcuts. So for now, I've commented them out. I've also added shortcuts for the other dialogs, and amended the language US/English file. If you want to test it out when you have time, and let me know if there's still weird things going, that would be great.

**Comment by olyop** [comment]
Thanks for getting back to me and commiting the changes to fix this. Agreed yes very strange! My best guess was a new browser version but who knows. I have applied the latest develop branch into our application and I can see this is working like before. All shortcuts are working no problems so happy for you to close this :)

Again thanks for your help, Oli

**Comment by DennisSuitters** [comment]
No worries, apologies it took as long as it did. Thanks for reporting.
